name: Java CI with Maven
on:
  
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:


jobs:
  build:
     runs-on: windows-latest
     steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: maven
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - name: Build with Maven
        run: mvn clean test
     
